project:
  type: website

website:
  title: "ISSS608 Visual Analytics and Applications"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

