project:
  type: website

website:
  title: "ISSS608 Visual Analytics and Applications"
  navbar:
    left:
    - text: "Hands-on Exercise"
    - text: "In-class Exercise"
    - text: "Take-home Exercise"
    right:
      - href: index.qmd
        text: Home


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

